DROP TABLE IF EXISTS Users CASCADE;
CREATE TABLE Users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(64),
  password VARCHAR(255) NOT NULL,
  email VARCHAR(64) NOT NULL,
  profile_pic_url VARCHAR(255) NOT NULL
);
