DROP TABLE IF EXISTS Products CASCADE;
CREATE TABLE Products (
  id SERIAL PRIMARY KEY NOT NULL,
  seller_id INTEGER REFERENCES Users(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES Categories(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price INTEGER NOT NULL,
  created_on TIMESTAMP DEFAULT NOW() NOT NULL,
  is_sold BOOLEAN DEFAULT FALSE,
  is_featured BOOLEAN DEFAULT FALSE,
  image_url VARCHAR(255)
);
