DROP TABLE IF EXISTS Favourites CASCADE;
CREATE TABLE Favourites (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES Products(id) ON DELETE CASCADE
);
